//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/Rest", ClrNamespace="schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.Rest")]

namespace schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.Rest
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingRequest", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/Rest")]
    public partial class BillingRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.QueryBillingEventParameters QueryBillingEventParametersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParameters
        {
            get
            {
                return this.PagingParametersField;
            }
            set
            {
                this.PagingParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.QueryBillingEventParameters QueryBillingEventParameters
        {
            get
            {
                return this.QueryBillingEventParametersField;
            }
            set
            {
                this.QueryBillingEventParametersField = value;
            }
        }
    }
}
