//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ipc.Billing
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing", ConfigurationName="Ipc.Billing.IDataServicesBilling")]
    public interface IDataServicesBilling
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common) of message PingRequest does not match the default value (http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common/IExternallyFacingS" +
            "tandardOperations/Ping", ReplyAction="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common/IExternallyFacingS" +
            "tandardOperations/PingResponse")]
        Ipc.Billing.PingResponse Ping(Ipc.Billing.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventSummary", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventSummaryDataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.BillingTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventSummaryBillingTransactionFailedFaultFault", Name="BillingTransactionFailedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventSummaryExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventSummaryInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventSummaryAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.BillingEventSummary> QueryBillingEventSummary(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.QueryBillingEventParameters queryBillingEventParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventDetail", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventDetailInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.BillingTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventDetailBillingTransactionFailedFaultFault", Name="BillingTransactionFailedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventDetailExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventDetailDataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/Billing/IDataServicesBilling/" +
            "QueryBillingEventDetailAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.BillingEventDetail> QueryBillingEventDetail(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.QueryBillingEventParameters queryBillingEventParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", IsWrapped=true)]
    public partial class PingRequest
    {
        
        public PingRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", IsWrapped=true)]
    public partial class PingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", Order=0)]
        public schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse PingResult;
        
        public PingResponse()
        {
        }
        
        public PingResponse(schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse PingResult)
        {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServicesBillingChannel : Ipc.Billing.IDataServicesBilling, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServicesBillingClient : System.ServiceModel.ClientBase<Ipc.Billing.IDataServicesBilling>, Ipc.Billing.IDataServicesBilling
    {
        
        public DataServicesBillingClient()
        {
        }
        
        public DataServicesBillingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DataServicesBillingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataServicesBillingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DataServicesBillingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ipc.Billing.PingResponse Ipc.Billing.IDataServicesBilling.Ping(Ipc.Billing.PingRequest request)
        {
            return base.Channel.Ping(request);
        }
        
        public schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse Ping()
        {
            Ipc.Billing.PingRequest inValue = new Ipc.Billing.PingRequest();
            Ipc.Billing.PingResponse retVal = ((Ipc.Billing.IDataServicesBilling)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.BillingEventSummary> QueryBillingEventSummary(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.QueryBillingEventParameters queryBillingEventParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryBillingEventSummary(sessionToken, queryBillingEventParameters, pagingParameters);
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.BillingEventDetail> QueryBillingEventDetail(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.Billing.QueryBillingEventParameters queryBillingEventParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryBillingEventDetail(sessionToken, queryBillingEventParameters, pagingParameters);
        }
    }
}
