//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ipc.SvcInfo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation", ConfigurationName="Ipc.SvcInfo.ICWSServiceInformation")]
    public interface ICWSServiceInformation
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common) of message PingRequest does not match the default value (http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common/IExternallyFacingS" +
            "tandardOperations/Ping", ReplyAction="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common/IExternallyFacingS" +
            "tandardOperations/PingResponse")]
        Ipc.SvcInfo.PingResponse Ping(Ipc.SvcInfo.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithToken", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithTokenSTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithTokenCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithTokenExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithTokenInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithTokenAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        string SignOnWithToken(string identityToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetServiceInformation", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetServiceInformationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetServiceInformationInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetServiceInformationExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetServiceInformationAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetServiceInformationCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetServiceInformationCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.ServiceInformation GetServiceInformation(string sessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationData", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationDataAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationDataInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationDataCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationDataCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationDataExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveApplicationDataCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        string SaveApplicationData(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.ApplicationData applicationData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationData", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationDataAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationDataCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationDataCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationDataInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationDataCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetApplicationDataExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.ApplicationData GetApplicationData(string sessionToken, string applicationProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationData", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationDataExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationDataCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationDataCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationDataInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationDataAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteApplicationDataCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        void DeleteApplicationData(string sessionToken, string applicationProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitialized", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitializedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitializedAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitializedCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitializedInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitializedCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitializedExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "IsMerchantProfileInitializedCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        bool IsMerchantProfileInitialized(string sessionToken, string serviceId, string merchantProfileId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfiles", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile> GetMerchantProfiles(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIds", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIdsCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIdsCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIdsExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIdsInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIdsAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileIdsCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        System.Collections.Generic.List<string> GetMerchantProfileIds(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileId", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileIdAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileIdCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileIdCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileIdCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileIdExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfilesByProfileIdInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile> GetMerchantProfilesByProfileId(string sessionToken, string merchantProfileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfile", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetMerchantProfileInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile GetMerchantProfile(string sessionToken, string merchantProfileId, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfile", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfileExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfileAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfileCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfileCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfileCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DeleteMerchantProfileInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        void DeleteMerchantProfile(string sessionToken, string merchantProfileId, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfiles", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfilesExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfilesInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfilesCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfilesCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfilesAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SaveMerchantProfilesCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        void SaveMerchantProfiles(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType, System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile> merchantProfiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKey", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKeyAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.PasswordExpiredFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKeyPasswordExpiredFaultFault", Name="PasswordExpiredFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKeySTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.LockedByAdminFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKeyLockedByAdminFaultFault", Name="LockedByAdminFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.OneTimePasswordFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKeyOneTimePasswordFaultFault", Name="OneTimePasswordFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.BadAttemptThresholdExceededFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnWithUsernamePasswordForServiceKeyBadAttemptThresholdExceededFaultFault", Name="BadAttemptThresholdExceededFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        string SignOnWithUsernamePasswordForServiceKey(string serviceKey, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ResetPasswordForServiceKey", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ResetPasswordForServiceKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ResetPasswordForServiceKeyAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ResetPasswordForServiceKeySTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SendEmailFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ResetPasswordForServiceKeySendEmailFaultFault", Name="SendEmailFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.GeneratePasswordFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ResetPasswordForServiceKeyGeneratePasswordFaultFault", Name="GeneratePasswordFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        void ResetPasswordForServiceKey(string serviceKey, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangePasswordForServiceKey", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangePasswordForServiceKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SendEmailFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangePasswordForServiceKeySendEmailFaultFault", Name="SendEmailFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangePasswordForServiceKeySTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.PasswordInvalidFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangePasswordForServiceKeyPasswordInvalidFaultFault", Name="PasswordInvalidFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.UserNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangePasswordForServiceKeyUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangePasswordForServiceKeyAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        void ChangePasswordForServiceKey(string serviceKey, string userName, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeUsernameForServiceKey", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeUsernameForServiceKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeUsernameForServiceKeyAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.UserNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeUsernameForServiceKeyUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SendEmailFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeUsernameForServiceKeySendEmailFaultFault", Name="SendEmailFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeUsernameForServiceKeySTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        void ChangeUsernameForServiceKey(string serviceKey, string userName, string password, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeEmailForServiceKey", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeEmailForServiceKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SendEmailFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeEmailForServiceKeySendEmailFaultFault", Name="SendEmailFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeEmailForServiceKeySTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeEmailForServiceKeyAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.UserNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeEmailForServiceKeyUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidEmailFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ChangeEmailForServiceKeyInvalidEmailFaultFault", Name="InvalidEmailFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        void ChangeEmailForServiceKey(string serviceKey, string userName, string password, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetPasswordExpirationForServiceKey", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetPasswordExpirationForServiceKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetPasswordExpirationForServiceKeySTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetPasswordExpirationForServiceKeyAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.UserNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetPasswordExpirationForServiceKeyUserNotFoundFaultFault", Name="UserNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.DateTime GetPasswordExpirationForServiceKey(string serviceKey, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfile", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSServiceInformationUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfileCWSServiceInformationUnavailableFaultFault", Name="CWSServiceInformationUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfileCWSFaultFault", Name="CWSFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfileExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfileInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfileAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.Faults.CWSValidationResultFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "ValidateMerchantProfileCWSValidationResultFaultFault", Name="CWSValidationResultFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/Faults")]
        void ValidateMerchantProfile(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile merchantProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Identity/1.0/GetAllClaims", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsSTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ClaimNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsClaimNotFoundFaultFault", Name="ClaimNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthorizationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.RelyingPartyNotAssociatedToSecurityDomainFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFault", Name="RelyingPartyNotAssociatedToSecurityDomainFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SystemFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetAllClaimsSystemFaultFault", Name="SystemFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> GetAllClaims(string authenticatingToken, string verifiedToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Identity/1.0/GetClaims", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ClaimNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsClaimNotFoundFaultFault", Name="ClaimNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthorizationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.RelyingPartyNotAssociatedToSecurityDomainFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsRelyingPartyNotAssociatedToSecurityDomainFaultFault", Name="RelyingPartyNotAssociatedToSecurityDomainFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SystemFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsSystemFaultFault", Name="SystemFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsSTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "GetClaimsInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<string> GetClaims(string authenticatingToken, string verifiedToken, System.Collections.Generic.List<string> claimNSs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Identity/1.0/Renew", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthorizationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.NonRenewableTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewNonRenewableTokenFaultFault", Name="NonRenewableTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SystemFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewSystemFaultFault", Name="SystemFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.STSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "RenewSTSUnavailableFaultFault", Name="STSUnavailableFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        string Renew(string authenticatingToken, string toRenewToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Identity/2.0/TokenCred/SignOnAndAddClaims", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnAndAddClaimsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ClaimMappingsNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnAndAddClaimsClaimMappingsNotFoundFaultFault", Name="ClaimMappingsNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnAndAddClaimsAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SystemFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnAndAddClaimsSystemFaultFault", Name="SystemFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnAndAddClaimsInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnAndAddClaimsExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthorizationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "SignOnAndAddClaimsAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        string SignOnAndAddClaims(string identityToken, System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> claims);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Identity/2.0/TokenCred/DelegatedSignOn", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DelegatedSignOnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DelegatedSignOnAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ClaimMappingsNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DelegatedSignOnClaimMappingsNotFoundFaultFault", Name="ClaimMappingsNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SystemFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DelegatedSignOnSystemFaultFault", Name="SystemFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DelegatedSignOnInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DelegatedSignOnExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthorizationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "DelegatedSignOnAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        string DelegatedSignOn(string identityToken, string onBehalfOfSk, System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> claims);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Identity/2.0/MultiTokenCred/FederatedSignOn", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthorizationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SystemFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnSystemFaultFault", Name="SystemFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ClaimMappingsNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnClaimMappingsNotFoundFaultFault", Name="ClaimMappingsNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        string FederatedSignOn(string identityToken, string externalDomainToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Identity/2.0/MultiTokenCred/FederatedSignOnAndAddCl" +
            "aims", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAndAddClaimsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ClaimMappingsNotFoundFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAndAddClaimsClaimMappingsNotFoundFaultFault", Name="ClaimMappingsNotFoundFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAndAddClaimsAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.SystemFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAndAddClaimsSystemFaultFault", Name="SystemFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthorizationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAndAddClaimsAuthorizationFaultFault", Name="AuthorizationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAndAddClaimsInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/ServiceInformation/ICWSServiceInformation/" +
            "FederatedSignOnAndAddClaimsExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        string FederatedSignOnAndAddClaims(string identityToken, string externalDomainToken, System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> claims);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", IsWrapped=true)]
    public partial class PingRequest
    {
        
        public PingRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", IsWrapped=true)]
    public partial class PingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", Order=0)]
        public schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse PingResult;
        
        public PingResponse()
        {
        }
        
        public PingResponse(schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse PingResult)
        {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICWSServiceInformationChannel : Ipc.SvcInfo.ICWSServiceInformation, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CWSServiceInformationClient : System.ServiceModel.ClientBase<Ipc.SvcInfo.ICWSServiceInformation>, Ipc.SvcInfo.ICWSServiceInformation
    {
        
        public CWSServiceInformationClient()
        {
        }
        
        public CWSServiceInformationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CWSServiceInformationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CWSServiceInformationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CWSServiceInformationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ipc.SvcInfo.PingResponse Ipc.SvcInfo.ICWSServiceInformation.Ping(Ipc.SvcInfo.PingRequest request)
        {
            return base.Channel.Ping(request);
        }
        
        public schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse Ping()
        {
            Ipc.SvcInfo.PingRequest inValue = new Ipc.SvcInfo.PingRequest();
            Ipc.SvcInfo.PingResponse retVal = ((Ipc.SvcInfo.ICWSServiceInformation)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        public string SignOnWithToken(string identityToken)
        {
            return base.Channel.SignOnWithToken(identityToken);
        }
        
        public schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.ServiceInformation GetServiceInformation(string sessionToken)
        {
            return base.Channel.GetServiceInformation(sessionToken);
        }
        
        public string SaveApplicationData(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.ApplicationData applicationData)
        {
            return base.Channel.SaveApplicationData(sessionToken, applicationData);
        }
        
        public schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.ApplicationData GetApplicationData(string sessionToken, string applicationProfileId)
        {
            return base.Channel.GetApplicationData(sessionToken, applicationProfileId);
        }
        
        public void DeleteApplicationData(string sessionToken, string applicationProfileId)
        {
            base.Channel.DeleteApplicationData(sessionToken, applicationProfileId);
        }
        
        public bool IsMerchantProfileInitialized(string sessionToken, string serviceId, string merchantProfileId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType)
        {
            return base.Channel.IsMerchantProfileInitialized(sessionToken, serviceId, merchantProfileId, tenderType);
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile> GetMerchantProfiles(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType)
        {
            return base.Channel.GetMerchantProfiles(sessionToken, serviceId, tenderType);
        }
        
        public System.Collections.Generic.List<string> GetMerchantProfileIds(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType)
        {
            return base.Channel.GetMerchantProfileIds(sessionToken, serviceId, tenderType);
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile> GetMerchantProfilesByProfileId(string sessionToken, string merchantProfileId)
        {
            return base.Channel.GetMerchantProfilesByProfileId(sessionToken, merchantProfileId);
        }
        
        public schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile GetMerchantProfile(string sessionToken, string merchantProfileId, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType)
        {
            return base.Channel.GetMerchantProfile(sessionToken, merchantProfileId, serviceId, tenderType);
        }
        
        public void DeleteMerchantProfile(string sessionToken, string merchantProfileId, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType)
        {
            base.Channel.DeleteMerchantProfile(sessionToken, merchantProfileId, serviceId, tenderType);
        }
        
        public void SaveMerchantProfiles(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType, System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile> merchantProfiles)
        {
            base.Channel.SaveMerchantProfiles(sessionToken, serviceId, tenderType, merchantProfiles);
        }
        
        public string SignOnWithUsernamePasswordForServiceKey(string serviceKey, string username, string password)
        {
            return base.Channel.SignOnWithUsernamePasswordForServiceKey(serviceKey, username, password);
        }
        
        public void ResetPasswordForServiceKey(string serviceKey, string userName)
        {
            base.Channel.ResetPasswordForServiceKey(serviceKey, userName);
        }
        
        public void ChangePasswordForServiceKey(string serviceKey, string userName, string password, string newPassword)
        {
            base.Channel.ChangePasswordForServiceKey(serviceKey, userName, password, newPassword);
        }
        
        public void ChangeUsernameForServiceKey(string serviceKey, string userName, string password, string newUsername)
        {
            base.Channel.ChangeUsernameForServiceKey(serviceKey, userName, password, newUsername);
        }
        
        public void ChangeEmailForServiceKey(string serviceKey, string userName, string password, string newEmail)
        {
            base.Channel.ChangeEmailForServiceKey(serviceKey, userName, password, newEmail);
        }
        
        public System.DateTime GetPasswordExpirationForServiceKey(string serviceKey, string userName, string password)
        {
            return base.Channel.GetPasswordExpirationForServiceKey(serviceKey, userName, password);
        }
        
        public void ValidateMerchantProfile(string sessionToken, string serviceId, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.TenderType tenderType, schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile merchantProfile)
        {
            base.Channel.ValidateMerchantProfile(sessionToken, serviceId, tenderType, merchantProfile);
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> GetAllClaims(string authenticatingToken, string verifiedToken)
        {
            return base.Channel.GetAllClaims(authenticatingToken, verifiedToken);
        }
        
        public System.Collections.Generic.List<string> GetClaims(string authenticatingToken, string verifiedToken, System.Collections.Generic.List<string> claimNSs)
        {
            return base.Channel.GetClaims(authenticatingToken, verifiedToken, claimNSs);
        }
        
        public string Renew(string authenticatingToken, string toRenewToken)
        {
            return base.Channel.Renew(authenticatingToken, toRenewToken);
        }
        
        public string SignOnAndAddClaims(string identityToken, System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> claims)
        {
            return base.Channel.SignOnAndAddClaims(identityToken, claims);
        }
        
        public string DelegatedSignOn(string identityToken, string onBehalfOfSk, System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> claims)
        {
            return base.Channel.DelegatedSignOn(identityToken, onBehalfOfSk, claims);
        }
        
        public string FederatedSignOn(string identityToken, string externalDomainToken)
        {
            return base.Channel.FederatedSignOn(identityToken, externalDomainToken);
        }
        
        public string FederatedSignOnAndAddClaims(string identityToken, string externalDomainToken, System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> claims)
        {
            return base.Channel.FederatedSignOnAndAddClaims(identityToken, externalDomainToken, claims);
        }
    }
}
