//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ipc.TMS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS", ConfigurationName="Ipc.TMS.ITMSOperations")]
    public interface ITMSOperations
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common) of message PingRequest does not match the default value (http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common/IExternallyFacingS" +
            "tandardOperations/Ping", ReplyAction="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common/IExternallyFacingS" +
            "tandardOperations/PingResponse")]
        Ipc.TMS.PingResponse Ping(Ipc.TMS.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "DataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnknownServiceKeyFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "TMSUnknownServiceKeyFaultFault", Name="TMSUnknownServiceKeyFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "ExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "InvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "AuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "TMSTransactionFailedFaultFault", Name="TMSTransactionFailedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSOperationNotSupportedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "TMSOperationNotSupportedFaultFault", Name="TMSOperationNotSupportedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryBatch" +
            "TMSUnavailableFaultFault", Name="TMSUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.BatchDetailData> QueryBatch(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryBatchParameters queryBatchParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamilies", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesTMSTransactionFailedFaultFault", Name="TMSTransactionFailedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesTMSUnavailableFaultFault", Name="TMSUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesDataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnknownServiceKeyFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesTMSUnknownServiceKeyFaultFault", Name="TMSUnknownServiceKeyFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionFamiliesExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.FamilyDetail> QueryTransactionFamilies(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters queryTransactionsParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetail", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailDataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailTMSTransactionFailedFaultFault", Name="TMSTransactionFailedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailTMSUnavailableFaultFault", Name="TMSUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnknownServiceKeyFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailTMSUnknownServiceKeyFaultFault", Name="TMSUnknownServiceKeyFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsDetailExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.TransactionDetail> QueryTransactionsDetail(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters queryTransactionsParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.TransactionDetailFormat transactionDetailFormat, bool includeRelated, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummary", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryTMSTransactionFailedFaultFault", Name="TMSTransactionFailedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnknownServiceKeyFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryTMSUnknownServiceKeyFaultFault", Name="TMSUnknownServiceKeyFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryDataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryTrans" +
            "actionsSummaryTMSUnavailableFaultFault", Name="TMSUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.SummaryDetail> QueryTransactionsSummary(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters queryTransactionsParameters, bool includeRelated, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummary", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryDataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnknownServiceKeyFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryTMSUnknownServiceKeyFaultFault", Name="TMSUnknownServiceKeyFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryTMSTransactionFailedFaultFault", Name="TMSTransactionFailedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSOperationNotSupportedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryTMSOperationNotSupportedFaultFault", Name="TMSOperationNotSupportedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedSummaryTMSUnavailableFaultFault", Name="TMSUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckQueryRejectedParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckingRejectedSummaryResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckingRejectedDetailResponse))]
        schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryResponse QueryRejectedSummary(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters queryRejectedParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetail", ReplyAction="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSOperationNotSupportedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailTMSOperationNotSupportedFaultFault", Name="TMSOperationNotSupportedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailTMSUnavailableFaultFault", Name="TMSUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSUnknownServiceKeyFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailTMSUnknownServiceKeyFaultFault", Name="TMSUnknownServiceKeyFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.DataServicesUnavailableFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailDataServicesUnavailableFaultFault", Name="DataServicesUnavailableFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.ExpiredTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailExpiredTokenFaultFault", Name="ExpiredTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.InvalidTokenFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailInvalidTokenFaultFault", Name="InvalidTokenFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.Identity._1._01.AuthenticationFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailAuthenticationFaultFault", Name="AuthenticationFault", Namespace="http://schemas.ipcommerce.com/Identity/1.0/")]
        [System.ServiceModel.FaultContractAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Faults.TMSTransactionFailedFault), Action="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/ITMSOperations/QueryRejec" +
            "tedDetailTMSTransactionFailedFaultFault", Name="TMSTransactionFailedFault", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Faults")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckQueryRejectedParameters))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckingRejectedSummaryResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckingRejectedDetailResponse))]
        schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryResponse QueryRejectedDetail(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters queryRejectedParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", IsWrapped=true)]
    public partial class PingRequest
    {
        
        public PingRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", IsWrapped=true)]
    public partial class PingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.ipcommerce.com/Ipc.General.WCF.Contracts.Common", Order=0)]
        public schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse PingResult;
        
        public PingResponse()
        {
        }
        
        public PingResponse(schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse PingResult)
        {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITMSOperationsChannel : Ipc.TMS.ITMSOperations, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMSOperationsClient : System.ServiceModel.ClientBase<Ipc.TMS.ITMSOperations>, Ipc.TMS.ITMSOperations
    {
        
        public TMSOperationsClient()
        {
        }
        
        public TMSOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TMSOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TMSOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TMSOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ipc.TMS.PingResponse Ipc.TMS.ITMSOperations.Ping(Ipc.TMS.PingRequest request)
        {
            return base.Channel.Ping(request);
        }
        
        public schemas.ipcommerce.com.Ipc.General.WCF.Contracts.Common.External.PingResponse Ping()
        {
            Ipc.TMS.PingRequest inValue = new Ipc.TMS.PingRequest();
            Ipc.TMS.PingResponse retVal = ((Ipc.TMS.ITMSOperations)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.BatchDetailData> QueryBatch(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryBatchParameters queryBatchParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryBatch(sessionToken, queryBatchParameters, pagingParameters);
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.FamilyDetail> QueryTransactionFamilies(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters queryTransactionsParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryTransactionFamilies(sessionToken, queryTransactionsParameters, pagingParameters);
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.TransactionDetail> QueryTransactionsDetail(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters queryTransactionsParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.TransactionDetailFormat transactionDetailFormat, bool includeRelated, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryTransactionsDetail(sessionToken, queryTransactionsParameters, transactionDetailFormat, includeRelated, pagingParameters);
        }
        
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.SummaryDetail> QueryTransactionsSummary(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters queryTransactionsParameters, bool includeRelated, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryTransactionsSummary(sessionToken, queryTransactionsParameters, includeRelated, pagingParameters);
        }
        
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryResponse QueryRejectedSummary(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters queryRejectedParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryRejectedSummary(sessionToken, queryRejectedParameters, pagingParameters);
        }
        
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryResponse QueryRejectedDetail(string sessionToken, schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters queryRejectedParameters, schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters pagingParameters)
        {
            return base.Channel.QueryRejectedDetail(sessionToken, queryRejectedParameters, pagingParameters);
        }
    }
}
