//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Rest", ClrNamespace="schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Rest")]

namespace schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.Rest
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryBatch", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Rest")]
    public partial class QueryBatch : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryBatchParameters QueryBatchParametersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParameters
        {
            get
            {
                return this.PagingParametersField;
            }
            set
            {
                this.PagingParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryBatchParameters QueryBatchParameters
        {
            get
            {
                return this.QueryBatchParametersField;
            }
            set
            {
                this.QueryBatchParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryRejectedDetail", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckQueryRejectedParameters))]
    public partial class QueryRejectedDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters QueryRejectedParametersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParameters
        {
            get
            {
                return this.PagingParametersField;
            }
            set
            {
                this.PagingParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters QueryRejectedParameters
        {
            get
            {
                return this.QueryRejectedParametersField;
            }
            set
            {
                this.QueryRejectedParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryRejectedSummary", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.ElectronicCheckQueryRejectedParameters))]
    public partial class QueryRejectedSummary : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters QueryRejectedParametersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParameters
        {
            get
            {
                return this.PagingParametersField;
            }
            set
            {
                this.PagingParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryRejectedParameters QueryRejectedParameters
        {
            get
            {
                return this.QueryRejectedParametersField;
            }
            set
            {
                this.QueryRejectedParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryTransactionsDetail", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Rest")]
    public partial class QueryTransactionsDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IncludeRelatedField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters QueryTransactionsParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.TransactionDetailFormat TransactionDetailFormatField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeRelated
        {
            get
            {
                return this.IncludeRelatedField;
            }
            set
            {
                this.IncludeRelatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParameters
        {
            get
            {
                return this.PagingParametersField;
            }
            set
            {
                this.PagingParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters QueryTransactionsParameters
        {
            get
            {
                return this.QueryTransactionsParametersField;
            }
            set
            {
                this.QueryTransactionsParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.TransactionDetailFormat TransactionDetailFormat
        {
            get
            {
                return this.TransactionDetailFormatField;
            }
            set
            {
                this.TransactionDetailFormatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryTransactionsFamilies", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Rest")]
    public partial class QueryTransactionsFamilies : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters QueryTransactionsParametersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParameters
        {
            get
            {
                return this.PagingParametersField;
            }
            set
            {
                this.PagingParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters QueryTransactionsParameters
        {
            get
            {
                return this.QueryTransactionsParametersField;
            }
            set
            {
                this.QueryTransactionsParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryTransactionsSummary", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/DataServices/TMS/Rest")]
    public partial class QueryTransactionsSummary : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IncludeRelatedField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParametersField;
        
        private schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters QueryTransactionsParametersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeRelated
        {
            get
            {
                return this.IncludeRelatedField;
            }
            set
            {
                this.IncludeRelatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.PagingParameters PagingParameters
        {
            get
            {
                return this.PagingParametersField;
            }
            set
            {
                this.PagingParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.DataServices.TMS.QueryTransactionsParameters QueryTransactionsParameters
        {
            get
            {
                return this.QueryTransactionsParametersField;
            }
            set
            {
                this.QueryTransactionsParametersField = value;
            }
        }
    }
}
