//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest", ClrNamespace="schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest")]

namespace schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeTransaction", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.Adjust))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.Capture))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.Acknowledge))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ManageAccountById))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.Undo))]
    public partial class ChangeTransaction : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationProfileIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationProfileId
        {
            get
            {
                return this.ApplicationProfileIdField;
            }
            set
            {
                this.ApplicationProfileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adjust", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class Adjust : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ChangeTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Adjust DifferenceDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Adjust DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Capture", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class Capture : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ChangeTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture DifferenceDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Acknowledge", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class Acknowledge : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ChangeTransaction
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManageAccountById", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class ManageAccountById : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ChangeTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Manage DifferenceDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Manage DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Undo", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class Undo : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ChangeTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Undo DifferenceDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Undo DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitTransaction", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeAndCaptureTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ReturnTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.DisburseTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ManageAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ReturnById))]
    public partial class SubmitTransaction : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationProfileIdField;
        
        private string MerchantProfileIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationProfileId
        {
            get
            {
                return this.ApplicationProfileIdField;
            }
            set
            {
                this.ApplicationProfileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantProfileId
        {
            get
            {
                return this.MerchantProfileIdField;
            }
            set
            {
                this.MerchantProfileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeTransaction", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeAndCaptureTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ReturnTransaction))]
    public partial class AuthorizeTransaction : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeAndCaptureTransaction", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class AuthorizeAndCaptureTransaction : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeTransaction
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnTransaction", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class ReturnTransaction : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeTransaction
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisburseTransaction", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class DisburseTransaction : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManageAccount", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class ManageAccount : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnById", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class ReturnById : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransaction
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Return DifferenceDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Return DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmitTransactionWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeTransactionWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeAndCaptureTransactionWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ReturnTransactionWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.DisburseWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ReturnByIdWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ManageAccountWithProfile))]
    public partial class SubmitTransactionWithProfile : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationProfileIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationProfileId
        {
            get
            {
                return this.ApplicationProfileIdField;
            }
            set
            {
                this.ApplicationProfileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeTransactionWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeAndCaptureTransactionWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.ReturnTransactionWithProfile))]
    public partial class AuthorizeTransactionWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransactionWithProfile
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfileField;
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfile
        {
            get
            {
                return this.MerchantProfileField;
            }
            set
            {
                this.MerchantProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeAndCaptureTransactionWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class AuthorizeAndCaptureTransactionWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeTransactionWithProfile
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnTransactionWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class ReturnTransactionWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.AuthorizeTransactionWithProfile
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisburseWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class DisburseWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransactionWithProfile
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfileField;
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfile
        {
            get
            {
                return this.MerchantProfileField;
            }
            set
            {
                this.MerchantProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnByIdWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class ReturnByIdWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransactionWithProfile
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Return DifferenceDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Return DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManageAccountWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class ManageAccountWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.SubmitTransactionWithProfile
    {
        
        private schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfileField;
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction TransactionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfile
        {
            get
            {
                return this.MerchantProfileField;
            }
            set
            {
                this.MerchantProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.Transaction Transaction
        {
            get
            {
                return this.TransactionField;
            }
            set
            {
                this.TransactionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureTransactions", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAll))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAllAsync))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAllWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAllAsyncWithProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureSelective))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureSelectiveAsync))]
    public partial class CaptureTransactions : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationProfileIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationProfileId
        {
            get
            {
                return this.ApplicationProfileIdField;
            }
            set
            {
                this.ApplicationProfileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureAll", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAllAsync))]
    public partial class CaptureAll : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureTransactions
    {
        
        private System.Collections.Generic.List<string> BatchIdsField;
        
        private System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture> DifferenceDataField;
        
        private string MerchantProfileIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> BatchIds
        {
            get
            {
                return this.BatchIdsField;
            }
            set
            {
                this.BatchIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture> DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantProfileId
        {
            get
            {
                return this.MerchantProfileIdField;
            }
            set
            {
                this.MerchantProfileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureAllAsync", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class CaptureAllAsync : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAll
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureAllWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAllAsyncWithProfile))]
    public partial class CaptureAllWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureTransactions
    {
        
        private System.Collections.Generic.List<string> BatchIdsField;
        
        private System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture> DifferenceDataField;
        
        private schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> BatchIds
        {
            get
            {
                return this.BatchIdsField;
            }
            set
            {
                this.BatchIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture> DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.ServiceInformation.MerchantProfile MerchantProfile
        {
            get
            {
                return this.MerchantProfileField;
            }
            set
            {
                this.MerchantProfileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureAllAsyncWithProfile", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class CaptureAllAsyncWithProfile : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureAllWithProfile
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureSelective", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureSelectiveAsync))]
    public partial class CaptureSelective : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureTransactions
    {
        
        private System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture> DifferenceDataField;
        
        private System.Collections.Generic.List<string> TransactionIdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<schemas.ipcommerce.com.CWS.v2._0.Transactions.Capture> DifferenceData
        {
            get
            {
                return this.DifferenceDataField;
            }
            set
            {
                this.DifferenceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> TransactionIds
        {
            get
            {
                return this.TransactionIdsField;
            }
            set
            {
                this.TransactionIdsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CaptureSelectiveAsync", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class CaptureSelectiveAsync : schemas.ipcommerce.com.CWS.v2._0.Transactions.Rest.CaptureSelective
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FederatedSignOn", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class FederatedSignOn : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> ClaimsField;
        
        private string ExternalDomainTokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<schemas.ipcommerce.com.Identity._1._01.ClaimMetaData> Claims
        {
            get
            {
                return this.ClaimsField;
            }
            set
            {
                this.ClaimsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalDomainToken
        {
            get
            {
                return this.ExternalDomainTokenField;
            }
            set
            {
                this.ExternalDomainTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionRequest", Namespace="http://schemas.ipcommerce.com/CWS/v2.0/Transactions/Rest")]
    public partial class TransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MerchantProfileIdField;
        
        private schemas.ipcommerce.com.CWS.v2._0.Transactions.TransactionTenderData TransactionTenderDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantProfileId
        {
            get
            {
                return this.MerchantProfileIdField;
            }
            set
            {
                this.MerchantProfileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public schemas.ipcommerce.com.CWS.v2._0.Transactions.TransactionTenderData TransactionTenderData
        {
            get
            {
                return this.TransactionTenderDataField;
            }
            set
            {
                this.TransactionTenderDataField = value;
            }
        }
    }
}
